#version: '3.8'
#
#services:
#  crm-2024-mysql:
#      image: mysql:8.0.36
#      ports:
#        - '${MYSQL_PORT:-3307}:3306'
#      environment:
#        MYSQL_USER: '${MYSQL_USER:-crm}'
#        MYSQL_PASSWORD: '${MYSQL_PASSWORD:-12q}'
#        MYSQL_DATABASE: '${MYSQL_DATABASE:-crm_school}'
#      volumes:
#        - ./crm-2024-api-mysql-db:/var/lib/mysql

#  crm-redis:
#    image: redis:7.2.3
#    ports:
#      - '${REDIS_PORT:-6379}:6379'
#    command: >
#      --requirepass '${REDIS_PASSWORD:-redispass}'
#    restart: unless-stopped
#


#version: '3.8'
#
#services:
#  crm-redis:
#    image: redis:7.2.3
#    ports:
#      - '${REDIS_PORT:-6379}:6379'
#    command: >
#      --requirepass '${REDIS_PASSWORD:-redispass}'
#    restart: unless-stopped
#
#  crm-2024-s3:
#    image: quay.io/minio/minio:latest
#    command: server /data --console-address ":9001"
#    restart: unless-stopped
#    ports:
#      - '8000:9000'
#      - '8001:9001'
#    volumes:
#      - ./crm-2024-api-s3-db:/usr/src/app/s3
#    environment:
#      MINIO_ROOT_USER: '${AWS_S3_ACCESS_KEY:-user}'
#      MINIO_ROOT_PASSWORD: '${AWS_S3_SECRET_KEY:-password}'
#
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile  # Вказуємо шлях до Dockerfile для побудови образу
#    ports:
#      - '3001:3001'
#    environment:
#      MYSQL_PORT: '${MYSQL_PORT:-3306}'
#      MYSQL_HOST: '${MYSQL_HOST:-owu.linkpc.net}'
#      MYSQL_USER: '${MYSQL_USER:-oktencrm}'
#      MYSQL_PASSWORD: '${MYSQL_PASSWORD:-12q12q}'
#      MYSQL_DATABASE: '${MYSQL_DATABASE:-oktencrm}'
#      REDIS_HOST: '${REDIS_HOST:-localhost}'
#      REDIS_PORT: '${REDIS_PORT:-6379}'
#      AWS_S3_REGION: '${AWS_S3_REGION:-us-east-1}'
#      AWS_S3_ACCESS_KEY: '${AWS_S3_ACCESS_KEY:-user}'
#      AWS_S3_SECRET_KEY: '${AWS_S3_SECRET_KEY:-password}'
#      AWS_S3_BUCKET_NAME: '${AWS_S3_BUCKET_NAME:-crm-s3}'
#      AWS_S3_BUCKET_URL: '${AWS_S3_BUCKET_URL:-http://localhost:8000/crm-s3}'
#      AWS_S3_ENDPOINT: '${AWS_S3_ENDPOINT:-http://localhost:8000}'
#    depends_on:
#      - crm-redis
#      - crm-2024-s3
#    env_file:
#      - ./environments/local.env  # Вказуємо шлях до .env файлу в папці environments
#
#volumes:
#  crm-2024-api-s3:
#  crm-2024-api-s3-db:
