version: '3.8'

services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - okten-crm-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: crm
      MYSQL_USER: crm
      MYSQL_PASSWORD: 12q
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - okten-crm-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "npm run migration:run && npm run start:local"
    env_file:
      - backend/environments/prod.env
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - okten-crm-network

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - okten-crm-network

volumes:
  redis_data:
  mysql_data:

networks:
  okten-crm-network:
    driver: bridge