version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/environments/local.env
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
          test: [ "CMD", "curl", "-f", "http://localhost:5000/api" ]
          interval: 30s
          timeout: 5s
          retries: 5
    networks:
      - app-network
    command: npm run start:dev

  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      volumes:
        - ./frontend:/app
        - /app/node_modules
        - ./frontend/dist:/app/dist
      environment:
        - VITE_API_URL=/api
        - WATCHPACK_POLLING=true
      ports:
        - "3000:3000"
      depends_on:
        backend:
          condition: service_healthy
      networks:
        - app-network
      command: npm run dev

  mysql:
    image: mysql:8.0
    env_file:
      - ./backend/environments/local.env
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
  redis:
    image: redis:7-alpine
    container_name: okten-crm-redis-1
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=/api
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql-data:
  redis_data:

networks:
  app-network:
    driver: bridge